/*
 *  go_model_generator.go
 *
 *  Copyright 2026 Pavel Konovalov
 *
 *  This file is part of libIEC61850.
 *
 *  libIEC61850 is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 */

package tools

import (
	"ModelGenerator/parser"
	"ModelGenerator/scl/model"
	"ModelGenerator/scl/types"
	"fmt"
	"io"
	"strings"
)

// RunGoModelGenerator generates a Go source file containing a BuildModel() function
// that constructs an imodel.IedModel for the libiec61850-Go library.
func RunGoModelGenerator(r io.Reader, output io.Writer, packageName, iedName, accessPointName string) error {
	sclParser, err := parser.NewSclParser(r, true)
	if err != nil {
		return err
	}

	var ied *model.IED
	if iedName == "" {
		ied = sclParser.GetFirstIed()
	} else {
		ied = sclParser.GetIedByName(iedName)
	}
	if ied == nil {
		return fmt.Errorf("no data model present in SCL file")
	}

	var accessPoint *model.AccessPoint
	if accessPointName != "" {
		accessPoint = ied.GetAccessPointByName(accessPointName)
	} else {
		accessPoint = ied.GetFirstAccessPoint()
	}
	if accessPoint == nil {
		return fmt.Errorf("no valid access point found")
	}

	td := sclParser.GetTypeDeclarations()
	ldevices := accessPoint.GetServer().GetLogicalDevices()

	g := &goModelGen{
		w:       output,
		td:      td,
		counter: 0,
	}

	if packageName == "" {
		packageName = "model"
	}

	fmt.Fprintln(output, "// Code generated by ModelGenerator gengolibmodel. DO NOT EDIT.")
	fmt.Fprintln(output)
	fmt.Fprintf(output, "package %s\n\n", packageName)
	fmt.Fprintln(output, `import (`)
	fmt.Fprintln(output, `	"github.com/PVKonovalov/libiec61850-Go/pkg/iec61850/common"`)
	fmt.Fprintln(output, `	imodel "github.com/PVKonovalov/libiec61850-Go/pkg/iec61850/model"`)
	fmt.Fprintln(output, `	"github.com/PVKonovalov/libiec61850-Go/pkg/mms"`)
	fmt.Fprintln(output, `)`)
	fmt.Fprintln(output)
	fmt.Fprintln(output, `// BuildModel constructs and returns the IEC 61850 data model.`)
	fmt.Fprintf(output, `func BuildModel() *imodel.IedModel {`+"\n")
	fmt.Fprintf(output, "\tiedModel := imodel.NewIedModel(%q)\n", ied.GetName())
	fmt.Fprintln(output)

	for _, ld := range ldevices {
		ldVar := g.newVar("ld")
		fmt.Fprintf(output, "\t// Logical Device: %s\n", ld.GetInst())
		fmt.Fprintf(output, "\t%s := imodel.NewLogicalDevice(%q, iedModel)\n", ldVar, ld.GetInst())
		if ld.GetLdName() != "" {
			fmt.Fprintf(output, "\t%s.LDName = %q\n", ldVar, ld.GetLdName())
		}
		fmt.Fprintln(output)

		for _, ln := range ld.GetLogicalNodes() {
			lnVar := g.newVar("ln")
			fmt.Fprintf(output, "\t// Logical Node: %s\n", ln.GetName())
			fmt.Fprintf(output, "\t%s := imodel.NewLogicalNode(%q, %s)\n", lnVar, ln.GetName(), ldVar)
			fmt.Fprintln(output)

			for _, do := range ln.GetDataObjects() {
				g.emitDO(do, lnVar)
			}

			for _, ds := range ln.GetDataSets() {
				g.emitDataSet(ds, ldVar, lnVar, ld.GetInst(), ln.GetName())
			}
		}
	}

	fmt.Fprintln(output, "\treturn iedModel")
	fmt.Fprintln(output, "}")

	return nil
}

type goModelGen struct {
	w       io.Writer
	td      *types.TypeDeclarations
	counter int
}

func (g *goModelGen) newVar(prefix string) string {
	g.counter++
	return fmt.Sprintf("%s%d", prefix, g.counter)
}

func (g *goModelGen) emitDO(do *model.DataObject, lnVar string) {
	count := do.GetCount()
	hasContent := len(do.GetDataAttributes()) > 0 || len(do.GetSubDataObjects()) > 0
	if count <= 1 {
		if hasContent {
			doVar := g.newVar("do")
			fmt.Fprintf(g.w, "\t%s := imodel.NewDataObject(%q, %s)\n", doVar, do.GetName(), lnVar)
			g.emitDOContent(do, doVar)
		} else {
			g.counter++ // keep counter consistent
			fmt.Fprintf(g.w, "\timodel.NewDataObject(%q, %s)\n", do.GetName(), lnVar)
		}
		fmt.Fprintln(g.w)
	} else {
		// Array of DOs
		for i := 0; i < count; i++ {
			name := fmt.Sprintf("%s%d", do.GetName(), i+1)
			if hasContent {
				doVar := g.newVar("do")
				fmt.Fprintf(g.w, "\t%s := imodel.NewDataObject(%q, %s)\n", doVar, name, lnVar)
				g.emitDOContent(do, doVar)
			} else {
				g.counter++
				fmt.Fprintf(g.w, "\timodel.NewDataObject(%q, %s)\n", name, lnVar)
			}
			fmt.Fprintln(g.w)
		}
	}
}

func (g *goModelGen) emitDOContent(do *model.DataObject, doVar string) {
	for _, da := range do.GetDataAttributes() {
		g.emitTopLevelDA(da, doVar)
	}
	for _, subDO := range do.GetSubDataObjects() {
		for _, da := range subDO.GetDataAttributes() {
			g.emitTopLevelDA(da, doVar)
		}
	}
}

// emitTopLevelDA emits a DA that is a direct child of a DataObject.
func (g *goModelGen) emitTopLevelDA(da *model.DataAttribute, parentVar string) {
	fc := da.GetFC()
	name := da.GetName()
	if da.IsBasicAttribute() {
		daVar := g.newVar("da")
		fmt.Fprintf(g.w, "\t%s := imodel.NewDataAttribute(%q, %s, %s, %s)\n",
			daVar, name, fcToGoConst(fc), atTypeToGoType(da.GetType()), parentVar)
		if t := triggerOptToGoConst(da.GetTriggerOptions()); t != "" {
			fmt.Fprintf(g.w, "\t%s.TriggerOptions = %s\n", daVar, t)
		}
		g.emitInitValue(daVar, da.GetType(), da.GetEffectiveValue(g.td))
	} else {
		// CONSTRUCTED: emit the DA with TypeConstructed, then recurse into sub-DAs.
		daVar := g.newVar("da")
		fmt.Fprintf(g.w, "\t%s := imodel.NewDataAttribute(%q, %s, common.TypeConstructed, %s)\n",
			daVar, name, fcToGoConst(fc), parentVar)
		if t := triggerOptToGoConst(da.GetTriggerOptions()); t != "" {
			fmt.Fprintf(g.w, "\t%s.TriggerOptions = %s\n", daVar, t)
		}
		for _, sub := range da.GetSubDataAttributes() {
			g.emitSubDA(sub, daVar, fc)
		}
	}
}

// emitSubDA emits a sub-DA (child of a CONSTRUCTED DataAttribute), using NewSubDataAttribute.
func (g *goModelGen) emitSubDA(da *model.DataAttribute, parentVar string, parentFC model.FunctionalConstraint) {
	fc := da.GetFC()
	if fc == model.FC_NONE {
		fc = parentFC
	}
	name := da.GetName()
	if da.IsBasicAttribute() {
		daVar := g.newVar("da")
		fmt.Fprintf(g.w, "\t%s := imodel.NewSubDataAttribute(%q, %s, %s, %s)\n",
			daVar, name, fcToGoConst(fc), atTypeToGoType(da.GetType()), parentVar)
		if t := triggerOptToGoConst(da.GetTriggerOptions()); t != "" {
			fmt.Fprintf(g.w, "\t%s.TriggerOptions = %s\n", daVar, t)
		}
		g.emitInitValue(daVar, da.GetType(), da.GetEffectiveValue(g.td))
	} else {
		daVar := g.newVar("da")
		fmt.Fprintf(g.w, "\t%s := imodel.NewSubDataAttribute(%q, %s, common.TypeConstructed, %s)\n",
			daVar, name, fcToGoConst(fc), parentVar)
		if t := triggerOptToGoConst(da.GetTriggerOptions()); t != "" {
			fmt.Fprintf(g.w, "\t%s.TriggerOptions = %s\n", daVar, t)
		}
		for _, sub := range da.GetSubDataAttributes() {
			g.emitSubDA(sub, daVar, fc)
		}
	}
}

func (g *goModelGen) emitInitValue(daVar string, atType model.AttributeType, val *model.DataModelValue) {
	if val == nil {
		// emit default zero value
		g.emitDefaultValue(daVar, atType)
		return
	}
	v := val.GetValue()
	if v == nil {
		g.emitDefaultValue(daVar, atType)
		return
	}
	switch atType {
	case model.AT_BOOLEAN:
		b, _ := v.(bool)
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewBoolean(%v)\n", daVar, b)
	case model.AT_INT8, model.AT_INT16, model.AT_INT32:
		n := val.GetIntValue()
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewInt32(%d)\n", daVar, n)
	case model.AT_INT64, model.AT_INT128:
		n := val.GetLongValue()
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewInt64(%d)\n", daVar, n)
	case model.AT_INT8U, model.AT_INT16U, model.AT_INT24U, model.AT_INT32U:
		n := val.GetIntValue()
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewUint32(%d)\n", daVar, n)
	case model.AT_FLOAT32:
		f, _ := v.(float32)
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewFloat32(%g)\n", daVar, f)
	case model.AT_FLOAT64:
		f, _ := v.(float64)
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewFloat64(%g)\n", daVar, f)
	case model.AT_ENUMERATED:
		n := val.GetIntValue()
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewInt32(%d)\n", daVar, n)
	case model.AT_VISIBLE_STRING_32, model.AT_VISIBLE_STRING_64, model.AT_VISIBLE_STRING_65,
		model.AT_VISIBLE_STRING_129, model.AT_VISIBLE_STRING_255, model.AT_UNICODE_STRING_255:
		s, _ := v.(string)
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewVisibleString(%q)\n", daVar, s)
	default:
		g.emitDefaultValue(daVar, atType)
	}
}

func (g *goModelGen) emitDefaultValue(daVar string, atType model.AttributeType) {
	switch atType {
	case model.AT_BOOLEAN:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewBoolean(false)\n", daVar)
	case model.AT_INT8, model.AT_INT16, model.AT_INT32, model.AT_ENUMERATED:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewInt32(0)\n", daVar)
	case model.AT_INT64, model.AT_INT128:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewInt64(0)\n", daVar)
	case model.AT_INT8U, model.AT_INT16U, model.AT_INT24U, model.AT_INT32U:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewUint32(0)\n", daVar)
	case model.AT_FLOAT32:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewFloat32(0)\n", daVar)
	case model.AT_FLOAT64:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewFloat64(0)\n", daVar)
	case model.AT_QUALITY:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewBitString([]byte{0x00, 0x00}, 13)\n", daVar)
	case model.AT_TIMESTAMP, model.AT_ENTRY_TIME:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewUTCTime(mms.UTCTime{})\n", daVar)
	case model.AT_VISIBLE_STRING_32, model.AT_VISIBLE_STRING_64, model.AT_VISIBLE_STRING_65,
		model.AT_VISIBLE_STRING_129, model.AT_VISIBLE_STRING_255, model.AT_UNICODE_STRING_255:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewVisibleString(\"\")\n", daVar)
	case model.AT_OCTET_STRING_6, model.AT_OCTET_STRING_8, model.AT_OCTET_STRING_64:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewOctetString(nil)\n", daVar)
	case model.AT_CODEDENUM:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewBitString([]byte{0x00}, 2)\n", daVar)
	case model.AT_GENERIC_BITSTRING:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewBitString(nil, 0)\n", daVar)
	case model.AT_CHECK:
		fmt.Fprintf(g.w, "\t%s.Value = mms.NewBitString([]byte{0x00}, 2)\n", daVar)
	default:
		// no default value for unknown types
		fmt.Fprintf(g.w, "\t_ = %s // TODO: set initial value for type %v\n", daVar, atType)
	}
}

func (g *goModelGen) emitDataSet(ds *model.DataSet, ldVar, lnVar, ldInst, lnName string) {
	dsName := lnName + "$" + ds.GetName()
	dsVar := g.newVar("ds")
	fmt.Fprintf(g.w, "\t%s := &imodel.DataSet{Name: %q}\n", dsVar, dsName)
	for _, fcda := range ds.GetFCDA() {
		ref := buildFCDARef(ldInst, fcda)
		goFC := fcToGoConst(fcda.GetFC())
		fmt.Fprintf(g.w, "\t%s.Members = append(%s.Members, imodel.DataSetMember{Reference: %q, FC: %s})\n",
			dsVar, dsVar, ref, goFC)
	}
	fmt.Fprintf(g.w, "\tiedModel.DataSets = append(iedModel.DataSets, %s)\n", dsVar)
	fmt.Fprintln(g.w)
}

func buildFCDARef(ldInst string, fcda *model.FunctionalConstraintData) string {
	var sb strings.Builder
	ld := fcda.GetLdInstance()
	if ld == "" {
		ld = ldInst
	}
	sb.WriteString(ld)
	sb.WriteByte('/')
	if fcda.GetPrefix() != "" {
		sb.WriteString(fcda.GetPrefix())
	}
	sb.WriteString(fcda.GetLnClass())
	sb.WriteString(fcda.GetLnInstance())
	sb.WriteByte('.')
	sb.WriteString(fcda.GetDoName())
	if fcda.GetDaName() != "" {
		sb.WriteByte('.')
		sb.WriteString(fcda.GetDaName())
	}
	return sb.String()
}

func atTypeToGoType(at model.AttributeType) string {
	switch at {
	case model.AT_BOOLEAN:
		return "common.TypeBoolean"
	case model.AT_INT8:
		return "common.TypeINT8"
	case model.AT_INT16:
		return "common.TypeINT16"
	case model.AT_INT32:
		return "common.TypeINT32"
	case model.AT_INT64:
		return "common.TypeINT64"
	case model.AT_INT128:
		return "common.TypeINT128"
	case model.AT_INT8U:
		return "common.TypeINT8U"
	case model.AT_INT16U:
		return "common.TypeINT16U"
	case model.AT_INT24U:
		return "common.TypeINT24U"
	case model.AT_INT32U:
		return "common.TypeINT32U"
	case model.AT_FLOAT32:
		return "common.TypeFLOAT32"
	case model.AT_FLOAT64:
		return "common.TypeFLOAT64"
	case model.AT_ENUMERATED:
		return "common.TypeEnumerated"
	case model.AT_OCTET_STRING_6:
		return "common.TypeOctetString6"
	case model.AT_OCTET_STRING_8:
		return "common.TypeOctetString8"
	case model.AT_OCTET_STRING_64:
		return "common.TypeOctetString64"
	case model.AT_VISIBLE_STRING_32:
		return "common.TypeVisibleStr32"
	case model.AT_VISIBLE_STRING_64:
		return "common.TypeVisibleStr64"
	case model.AT_VISIBLE_STRING_65:
		return "common.TypeVisibleStr65"
	case model.AT_VISIBLE_STRING_129:
		return "common.TypeVisibleStr129"
	case model.AT_VISIBLE_STRING_255:
		return "common.TypeVisibleStr255"
	case model.AT_UNICODE_STRING_255:
		return "common.TypeUnicodeStr255"
	case model.AT_TIMESTAMP:
		return "common.TypeTimestamp"
	case model.AT_QUALITY:
		return "common.TypeQuality"
	case model.AT_CHECK:
		return "common.TypeCheck"
	case model.AT_CODEDENUM:
		return "common.TypeCodedEnum"
	case model.AT_GENERIC_BITSTRING:
		return "common.TypeGenericBitStr"
	case model.AT_CONSTRUCTED:
		return "common.TypeConstructed"
	case model.AT_ENTRY_TIME:
		return "common.TypeEntryTime"
	default:
		return fmt.Sprintf("common.TypeUnknown /* %v */", at)
	}
}

func fcToGoConst(fc model.FunctionalConstraint) string {
	switch fc {
	case model.FC_ST:
		return "common.FC_ST"
	case model.FC_MX:
		return "common.FC_MX"
	case model.FC_SP:
		return "common.FC_SP"
	case model.FC_SV:
		return "common.FC_SV"
	case model.FC_CF:
		return "common.FC_CF"
	case model.FC_DC:
		return "common.FC_DC"
	case model.FC_SG:
		return "common.FC_SG"
	case model.FC_SE:
		return "common.FC_SE"
	case model.FC_SR:
		return "common.FC_SR"
	case model.FC_OR:
		return "common.FC_OR"
	case model.FC_BL:
		return "common.FC_BL"
	case model.FC_EX:
		return "common.FC_EX"
	case model.FC_CO:
		return "common.FC_CO"
	default:
		return "common.FC_NONE"
	}
}

func triggerOptToGoConst(t *model.TriggerOptions) string {
	if t == nil {
		return ""
	}
	var parts []string
	if t.IsDchg() {
		parts = append(parts, "common.TriggerDataChanged")
	}
	if t.IsQchg() {
		parts = append(parts, "common.TriggerQualityChanged")
	}
	if t.IsDupd() {
		parts = append(parts, "common.TriggerDataUpdate")
	}
	if t.IsPeriod() {
		parts = append(parts, "common.TriggerIntegrity")
	}
	if t.IsGI() {
		parts = append(parts, "common.TriggerGI")
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " | ")
}
